//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accord.Tests.Statistics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accord.Tests.Statistics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CircleWithWeights {
            get {
                object obj = ResourceManager.GetObject("CircleWithWeights", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In1,In2,Out
        ///15.3,0,1
        ///15,0,1
        ///3.2,1,1
        ///7.5,0,0
        ///10.2,0,1
        ///10.9,0,1
        ///14.5,0,0
        ///5.7,0,0
        ///5,0,1
        ///12.5,0,1
        ///10,0,0
        ///7.2,0,1
        ///13,0,1
        ///5.7,0,0
        ///6.8,0,1
        ///7.81,0,0
        ///14.3,0,0
        ///12.3,0,1
        ///9,0,1
        ///5,0,1
        ///4.8,0,0
        ///2.79,0,1
        ///7,0,0
        ///8.33,0,1
        ///14,0,1
        ///10.3,0,1
        ///11,0,1
        ///6.41,0,0
        ///6.77,0,1
        ///7.52,0,1
        ///5.67,0,1
        ///6.94,0,1
        ///6.86,0,1
        ///4.8,0,1
        ///6.8,0,1
        ///4.2,0,1
        ///6.1,0,1
        ///5.53,0,1
        ///12.6,0,0
        ///13,0,1
        ///7.2,0,0
        ///14,0,1
        ///12.2,0,1
        ///7.49,0,1
        ///10.2,0,1
        ///16.2,0,1
        ///7,0,0
        ///8,0,1
        ///4.5,0,1
        ///5.02,0,1
        ///6.7,0,1
        ///16.2,0,1
        ///13.7,0,1
        ///10.2,0,1
        ///5.09, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string regression {
            get {
                return ResourceManager.GetString("regression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sample {
            get {
                object obj = ResourceManager.GetObject("sample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sample1 {
            get {
                object obj = ResourceManager.GetObject("sample1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
