// This file was generated automatically by the Snowball to C# compiler

#pragma warning disable 0164
#pragma warning disable 0162

namespace Accord.MachineLearning.Text.Stemmers
{
    using System;
    using System.Text;
    
    ///<summary>
    ///  This class was automatically generated by a Snowball to C# compiler 
    ///  It implements the stemming algorithm defined by a snowball script.
    ///</summary>
    /// 
    [System.CodeDom.Compiler.GeneratedCode("Snowball", "1.0.0")]
    public partial class PorterStemmer : StemmerBase
    {
        private bool B_Y_found;
        private int I_p2;
        private int I_p1;

        private static string g_v = "aeiouy";
        private static string g_v_WXY = "aeiouywxY";
        private readonly Among[] a_0;
        private readonly Among[] a_1;
        private readonly Among[] a_2;
        private readonly Among[] a_3;
        private readonly Among[] a_4;
        private readonly Among[] a_5;

        /// <summary>
        ///   Initializes a new instance of the <see cref="PorterStemmer"/> class.
        /// </summary>
        /// 
        public PorterStemmer()
        {
            a_0 = new[] 
            {
                new Among("s", -1, 3),
                new Among("ies", 0, 2),
                new Among("sses", 0, 1),
                new Among("ss", 0, -1)
            };

            a_1 = new[] 
            {
                new Among("", -1, 3),
                new Among("bb", 0, 2),
                new Among("dd", 0, 2),
                new Among("ff", 0, 2),
                new Among("gg", 0, 2),
                new Among("bl", 0, 1),
                new Among("mm", 0, 2),
                new Among("nn", 0, 2),
                new Among("pp", 0, 2),
                new Among("rr", 0, 2),
                new Among("at", 0, 1),
                new Among("tt", 0, 2),
                new Among("iz", 0, 1)
            };

            a_2 = new[] 
            {
                new Among("ed", -1, 2),
                new Among("eed", 0, 1),
                new Among("ing", -1, 2)
            };

            a_3 = new[] 
            {
                new Among("anci", -1, 3),
                new Among("enci", -1, 2),
                new Among("abli", -1, 4),
                new Among("eli", -1, 6),
                new Among("alli", -1, 9),
                new Among("ousli", -1, 12),
                new Among("entli", -1, 5),
                new Among("aliti", -1, 10),
                new Among("biliti", -1, 14),
                new Among("iviti", -1, 13),
                new Among("tional", -1, 1),
                new Among("ational", 10, 8),
                new Among("alism", -1, 10),
                new Among("ation", -1, 8),
                new Among("ization", 13, 7),
                new Among("izer", -1, 7),
                new Among("ator", -1, 8),
                new Among("iveness", -1, 13),
                new Among("fulness", -1, 11),
                new Among("ousness", -1, 12)
            };

            a_4 = new[] 
            {
                new Among("icate", -1, 2),
                new Among("ative", -1, 3),
                new Among("alize", -1, 1),
                new Among("iciti", -1, 2),
                new Among("ical", -1, 2),
                new Among("ful", -1, 3),
                new Among("ness", -1, 3)
            };

            a_5 = new[] 
            {
                new Among("ic", -1, 1),
                new Among("ance", -1, 1),
                new Among("ence", -1, 1),
                new Among("able", -1, 1),
                new Among("ible", -1, 1),
                new Among("ate", -1, 1),
                new Among("ive", -1, 1),
                new Among("ize", -1, 1),
                new Among("iti", -1, 1),
                new Among("al", -1, 1),
                new Among("ism", -1, 1),
                new Among("ion", -1, 2),
                new Among("er", -1, 1),
                new Among("ous", -1, 1),
                new Among("ant", -1, 1),
                new Among("ent", -1, 1),
                new Among("ment", 15, 1),
                new Among("ement", 16, 1),
                new Among("ou", -1, 1)
            };

        }



        private int r_shortv()
        {
            // (, line 19
            if (out_grouping_b(g_v_WXY, 89, 121, false) != 0)
            {
                return 0;
            }
            if (in_grouping_b(g_v, 97, 121, false) != 0)
            {
                return 0;
            }
            if (out_grouping_b(g_v, 97, 121, false) != 0)
            {
                return 0;
            }

            return 1;
        }

        private int r_R1()
        {
            if (!(I_p1 <= cursor))
            {
                return 0;
            }

            return 1;
        }

        private int r_R2()
        {
            if (!(I_p2 <= cursor))
            {
                return 0;
            }

            return 1;
        }

        private int r_Step_1a()
        {
            int among_var;
            // (, line 24
            // [, line 25
            ket = cursor;
            // substring, line 25
            among_var = find_among_b(a_0);
            if (among_var == 0)
            {
                return 0;
            }
            // ], line 25
            bra = cursor;
            switch (among_var) 
            {
                case 0:
                    {
                        return 0;
                    }
                case 1:
                    // (, line 26
                    // <-, line 26
                    slice_from("ss");
                    break;
                case 2:
                    // (, line 27
                    // <-, line 27
                    slice_from("i");
                    break;
                case 3:
                    // (, line 29
                    // delete, line 29
                    slice_del();
                    break;
            }

            return 1;
        }

        private int r_Step_1b()
        {
            int among_var;
            // (, line 33
            // [, line 34
            ket = cursor;
            // substring, line 34
            among_var = find_among_b(a_2);
            if (among_var == 0)
            {
                return 0;
            }
            // ], line 34
            bra = cursor;
            switch (among_var) 
            {
                case 0:
                    {
                        return 0;
                    }
                case 1:
                    // (, line 35
                    {
                        // call R1, line 35
                        int ret = r_R1();
                        if (ret == 0)
                            return 0;
                        else if (ret < 0)
                            return ret;
                    }
                    // <-, line 35
                    slice_from("ee");
                    break;
                case 2:
                    // (, line 37
                    // test, line 38
                    {
                        int c1 = limit - cursor;
                        {
                            /* gopast */ 
                            int ret = out_grouping_b(g_v, 97, 121, true);
                            if (ret < 0)
                            {
                                return 0;
                            }

                            cursor -= ret;
                        }
                        cursor = limit - c1;
                    }
                    // delete, line 38
                    slice_del();
                    // test, line 39
                    {
                        int c3 = limit - cursor;
                        // substring, line 39
                        among_var = find_among_b(a_1);
                        if (among_var == 0)
                        {
                            return 0;
                        }
                        cursor = limit - c3;
                    }
                    switch (among_var) 
                    {
                        case 0:
                            {
                                return 0;
                            }
                        case 1:
                            // (, line 41
                            // <+, line 41
                            {
                                int c = cursor;
                                insert(cursor, cursor, "e");
                                cursor = c;
                            }
                            break;
                        case 2:
                            // (, line 44
                            // [, line 44
                            ket = cursor;
                            // next, line 44
                            if (cursor <= limit_backward)
                            {
                                return 0;
                            }
                            cursor--;
                            // ], line 44
                            bra = cursor;
                            // delete, line 44
                            slice_del();
                            break;
                        case 3:
                            // (, line 45
                            // atmark, line 45
                            if (cursor != I_p1)
                            {
                                return 0;
                            }
                            // test, line 45
                            {
                                int c4 = limit - cursor;
                                {
                                    // call shortv, line 45
                                    int ret = r_shortv();
                                    if (ret == 0)
                                        return 0;
                                    else if (ret < 0)
                                        return ret;
                                }
                                cursor = limit - c4;
                            }
                            // <+, line 45
                            {
                                int c = cursor;
                                insert(cursor, cursor, "e");
                                cursor = c;
                            }
                            break;
                    }
                    break;
            }

            return 1;
        }

        private int r_Step_1c()
        {
            // (, line 51
            // [, line 52
            ket = cursor;
            // or, line 52
            {
                int c1 = limit - cursor;
                // literal, line 52
                if (!(eq_s_b("y")))
                {
                    goto lab1;
                }
                goto lab0;
            lab1: ; 
                cursor = limit - c1;
                // literal, line 52
                if (!(eq_s_b("Y")))
                {
                    return 0;
                }
            }
        lab0: ; 
            // ], line 52
            bra = cursor;
            {
                /* gopast */ 
                int ret = out_grouping_b(g_v, 97, 121, true);
                if (ret < 0)
                {
                    return 0;
                }

                cursor -= ret;
            }
            // <-, line 54
            slice_from("i");

            return 1;
        }

        private int r_Step_2()
        {
            int among_var;
            // (, line 57
            // [, line 58
            ket = cursor;
            // substring, line 58
            among_var = find_among_b(a_3);
            if (among_var == 0)
            {
                return 0;
            }
            // ], line 58
            bra = cursor;
            {
                // call R1, line 58
                int ret = r_R1();
                if (ret == 0)
                    return 0;
                else if (ret < 0)
                    return ret;
            }
            switch (among_var) 
            {
                case 0:
                    {
                        return 0;
                    }
                case 1:
                    // (, line 59
                    // <-, line 59
                    slice_from("tion");
                    break;
                case 2:
                    // (, line 60
                    // <-, line 60
                    slice_from("ence");
                    break;
                case 3:
                    // (, line 61
                    // <-, line 61
                    slice_from("ance");
                    break;
                case 4:
                    // (, line 62
                    // <-, line 62
                    slice_from("able");
                    break;
                case 5:
                    // (, line 63
                    // <-, line 63
                    slice_from("ent");
                    break;
                case 6:
                    // (, line 64
                    // <-, line 64
                    slice_from("e");
                    break;
                case 7:
                    // (, line 66
                    // <-, line 66
                    slice_from("ize");
                    break;
                case 8:
                    // (, line 68
                    // <-, line 68
                    slice_from("ate");
                    break;
                case 9:
                    // (, line 69
                    // <-, line 69
                    slice_from("al");
                    break;
                case 10:
                    // (, line 71
                    // <-, line 71
                    slice_from("al");
                    break;
                case 11:
                    // (, line 72
                    // <-, line 72
                    slice_from("ful");
                    break;
                case 12:
                    // (, line 74
                    // <-, line 74
                    slice_from("ous");
                    break;
                case 13:
                    // (, line 76
                    // <-, line 76
                    slice_from("ive");
                    break;
                case 14:
                    // (, line 77
                    // <-, line 77
                    slice_from("ble");
                    break;
            }

            return 1;
        }

        private int r_Step_3()
        {
            int among_var;
            // (, line 81
            // [, line 82
            ket = cursor;
            // substring, line 82
            among_var = find_among_b(a_4);
            if (among_var == 0)
            {
                return 0;
            }
            // ], line 82
            bra = cursor;
            {
                // call R1, line 82
                int ret = r_R1();
                if (ret == 0)
                    return 0;
                else if (ret < 0)
                    return ret;
            }
            switch (among_var) 
            {
                case 0:
                    {
                        return 0;
                    }
                case 1:
                    // (, line 83
                    // <-, line 83
                    slice_from("al");
                    break;
                case 2:
                    // (, line 85
                    // <-, line 85
                    slice_from("ic");
                    break;
                case 3:
                    // (, line 87
                    // delete, line 87
                    slice_del();
                    break;
            }

            return 1;
        }

        private int r_Step_4()
        {
            int among_var;
            // (, line 91
            // [, line 92
            ket = cursor;
            // substring, line 92
            among_var = find_among_b(a_5);
            if (among_var == 0)
            {
                return 0;
            }
            // ], line 92
            bra = cursor;
            {
                // call R2, line 92
                int ret = r_R2();
                if (ret == 0)
                    return 0;
                else if (ret < 0)
                    return ret;
            }
            switch (among_var) 
            {
                case 0:
                    {
                        return 0;
                    }
                case 1:
                    // (, line 95
                    // delete, line 95
                    slice_del();
                    break;
                case 2:
                    // (, line 96
                    // or, line 96
                    {
                        int c1 = limit - cursor;
                        // literal, line 96
                        if (!(eq_s_b("s")))
                        {
                            goto lab1;
                        }
                        goto lab0;
                    lab1: ; 
                        cursor = limit - c1;
                        // literal, line 96
                        if (!(eq_s_b("t")))
                        {
                            return 0;
                        }
                    }
                lab0: ; 
                    // delete, line 96
                    slice_del();
                    break;
            }

            return 1;
        }

        private int r_Step_5a()
        {
            // (, line 100
            // [, line 101
            ket = cursor;
            // literal, line 101
            if (!(eq_s_b("e")))
            {
                return 0;
            }
            // ], line 101
            bra = cursor;
            // or, line 102
            {
                int c1 = limit - cursor;
                {
                    // call R2, line 102
                    int ret = r_R2();
                    if (ret == 0)
                        goto lab1;
                    else if (ret < 0)
                        return ret;
                }
                goto lab0;
            lab1: ; 
                cursor = limit - c1;
                // (, line 102
                {
                    // call R1, line 102
                    int ret = r_R1();
                    if (ret == 0)
                        return 0;
                    else if (ret < 0)
                        return ret;
                }
                // not, line 102
                {
                    int c2 = limit - cursor;
                    {
                        // call shortv, line 102
                        int ret = r_shortv();
                        if (ret == 0)
                            goto lab2;
                        else if (ret < 0)
                            return ret;
                    }
                    return 0;
                lab2: ; 
                    cursor = limit - c2;
                }
            }
        lab0: ; 
            // delete, line 103
            slice_del();

            return 1;
        }

        private int r_Step_5b()
        {
            // (, line 106
            // [, line 107
            ket = cursor;
            // literal, line 107
            if (!(eq_s_b("l")))
            {
                return 0;
            }
            // ], line 107
            bra = cursor;
            {
                // call R2, line 108
                int ret = r_R2();
                if (ret == 0)
                    return 0;
                else if (ret < 0)
                    return ret;
            }
            // literal, line 108
            if (!(eq_s_b("l")))
            {
                return 0;
            }
            // delete, line 109
            slice_del();

            return 1;
        }

        private int stem()
        {
            // (, line 113
            // unset Y_found, line 115
            B_Y_found = false;
            // do, line 116
            {
                int c1 = cursor;
                // (, line 116
                // [, line 116
                bra = cursor;
                // literal, line 116
                if (!(eq_s("y")))
                {
                    goto lab0;
                }
                // ], line 116
                ket = cursor;
                // <-, line 116
                slice_from("Y");
                // set Y_found, line 116
                B_Y_found = true;
            lab0: ; 
                cursor = c1;
            }
            // do, line 117
            {
                int c2 = cursor;
                // repeat, line 117
                while (true)
                {
                    int c3 = cursor;
                    // (, line 117
                    while (true)
                    {
                        // goto, line 117
                        int c4 = cursor;
                        // (, line 117
                        if (in_grouping(g_v, 97, 121, false) != 0)
                        {
                            goto lab3;
                        }
                        // [, line 117
                        bra = cursor;
                        // literal, line 117
                        if (!(eq_s("y")))
                        {
                            goto lab3;
                        }
                        // ], line 117
                        ket = cursor;
                        cursor = c4;
                        break;
                    lab3: ; 
                        cursor = c4;
                        // goto, line 117
                        if (cursor >= limit)
                        {
                            goto lab2;
                        }
                        cursor++;
                    }
                    // <-, line 117
                    slice_from("Y");
                    // set Y_found, line 117
                    B_Y_found = true;
                    continue;
                lab2: ; 
                    cursor = c3;
                    break;
                }
                cursor = c2;
            }
            I_p1 = limit;
            I_p2 = limit;
            // do, line 121
            {
                int c5 = cursor;
                // (, line 121
                {
                    /* gopast */ 
                    int ret = out_grouping(g_v, 97, 121, true);
                    if (ret < 0)
                    {
                        goto lab4;
                    }

                    cursor += ret;
                }
                {
                    /* gopast */ 
                    int ret = in_grouping(g_v, 97, 121, true);
                    if (ret < 0)
                    {
                        goto lab4;
                    }

                    cursor += ret;
                }
                // setmark p1, line 122
                I_p1 = cursor;
                {
                    /* gopast */ 
                    int ret = out_grouping(g_v, 97, 121, true);
                    if (ret < 0)
                    {
                        goto lab4;
                    }

                    cursor += ret;
                }
                {
                    /* gopast */ 
                    int ret = in_grouping(g_v, 97, 121, true);
                    if (ret < 0)
                    {
                        goto lab4;
                    }

                    cursor += ret;
                }
                // setmark p2, line 123
                I_p2 = cursor;
            lab4: ; 
                cursor = c5;
            }
            // backwards, line 126
            limit_backward = cursor; cursor = limit;
            // (, line 126
            // do, line 127
            {
                int c10 = limit - cursor;
                {
                    // call Step_1a, line 127
                    int ret = r_Step_1a();
                    if (ret == 0)
                        goto lab5;
                    else if (ret < 0)
                        return ret;
                }
            lab5: ; 
                cursor = limit - c10;
            }
            // do, line 128
            {
                int c11 = limit - cursor;
                {
                    // call Step_1b, line 128
                    int ret = r_Step_1b();
                    if (ret == 0)
                        goto lab6;
                    else if (ret < 0)
                        return ret;
                }
            lab6: ; 
                cursor = limit - c11;
            }
            // do, line 129
            {
                int c12 = limit - cursor;
                {
                    // call Step_1c, line 129
                    int ret = r_Step_1c();
                    if (ret == 0)
                        goto lab7;
                    else if (ret < 0)
                        return ret;
                }
            lab7: ; 
                cursor = limit - c12;
            }
            // do, line 130
            {
                int c13 = limit - cursor;
                {
                    // call Step_2, line 130
                    int ret = r_Step_2();
                    if (ret == 0)
                        goto lab8;
                    else if (ret < 0)
                        return ret;
                }
            lab8: ; 
                cursor = limit - c13;
            }
            // do, line 131
            {
                int c14 = limit - cursor;
                {
                    // call Step_3, line 131
                    int ret = r_Step_3();
                    if (ret == 0)
                        goto lab9;
                    else if (ret < 0)
                        return ret;
                }
            lab9: ; 
                cursor = limit - c14;
            }
            // do, line 132
            {
                int c15 = limit - cursor;
                {
                    // call Step_4, line 132
                    int ret = r_Step_4();
                    if (ret == 0)
                        goto lab10;
                    else if (ret < 0)
                        return ret;
                }
            lab10: ; 
                cursor = limit - c15;
            }
            // do, line 133
            {
                int c16 = limit - cursor;
                {
                    // call Step_5a, line 133
                    int ret = r_Step_5a();
                    if (ret == 0)
                        goto lab11;
                    else if (ret < 0)
                        return ret;
                }
            lab11: ; 
                cursor = limit - c16;
            }
            // do, line 134
            {
                int c17 = limit - cursor;
                {
                    // call Step_5b, line 134
                    int ret = r_Step_5b();
                    if (ret == 0)
                        goto lab12;
                    else if (ret < 0)
                        return ret;
                }
            lab12: ; 
                cursor = limit - c17;
            }
            cursor = limit_backward;
            // do, line 137
            {
                int c18 = cursor;
                // (, line 137
                // Boolean test Y_found, line 137
                if (!(B_Y_found))
                {
                    goto lab13;
                }
                // repeat, line 137
                while (true)
                {
                    int c19 = cursor;
                    // (, line 137
                    while (true)
                    {
                        // goto, line 137
                        int c20 = cursor;
                        // (, line 137
                        // [, line 137
                        bra = cursor;
                        // literal, line 137
                        if (!(eq_s("Y")))
                        {
                            goto lab15;
                        }
                        // ], line 137
                        ket = cursor;
                        cursor = c20;
                        break;
                    lab15: ; 
                        cursor = c20;
                        // goto, line 137
                        if (cursor >= limit)
                        {
                            goto lab14;
                        }
                        cursor++;
                    }
                    // <-, line 137
                    slice_from("y");
                    continue;
                lab14: ; 
                    cursor = c19;
                    break;
                }
            lab13: ; 
                cursor = c18;
            }

            return 1;
        }

        /// <summary>
        ///   Stems the buffer's contents.
        /// </summary>
        /// 
        protected override bool Process()
        {
            return this.stem() > 0;
        }

    }
}

