using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Accord.Math")]
[assembly: InternalsVisibleTo("Accord.Statistics")]
[assembly: InternalsVisibleTo("Accord.Imaging")]
[assembly: InternalsVisibleTo("Accord.DataSets")]
[assembly: InternalsVisibleTo("Accord.MachineLearning")]
[assembly: InternalsVisibleTo("Accord.IO")]
[assembly: InternalsVisibleTo("Accord.Audio")]
[assembly: InternalsVisibleTo("Accord.Neuro")]
[assembly: InternalsVisibleTo("Accord.Video")]
[assembly: InternalsVisibleTo("Accord.Vision")]
[assembly: InternalsVisibleTo("Accord.Audition")]
[assembly: InternalsVisibleTo("Accord.Genetic")]
[assembly: InternalsVisibleTo("Accord.Audio.DirectSound")]

[assembly: InternalsVisibleTo("Accord.Tests.Core")]
[assembly: InternalsVisibleTo("Accord.Tests.IO")]
[assembly: InternalsVisibleTo("Accord.Tests.Math")]
[assembly: InternalsVisibleTo("Accord.Tests.Statistics")]
[assembly: InternalsVisibleTo("Accord.Tests.Imaging")]
[assembly: InternalsVisibleTo("Accord.Tests.Text")]
[assembly: InternalsVisibleTo("Accord.Tests.IO")]
[assembly: InternalsVisibleTo("Accord.Tests.MachineLearning")]
[assembly: InternalsVisibleTo("Accord.Tests.Math.Interop")]
[assembly: InternalsVisibleTo("Accord.Tests.Interop.Math")]
