
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
 
using System.Reflection;

[assembly: AssemblyProduct("Accord.NET Framework")]
[assembly: AssemblyCopyright("Copyright © Accord.NET authors, 2009-2015")]
[assembly: AssemblyCompany("Accord.NET")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyVersion("3.0.2")]
[assembly: AssemblyInformationalVersion("3.0.2")]
[assembly: AssemblyFileVersion("3.0.2.5282")]
