// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
 
using System.Reflection;

[assembly: AssemblyProduct("Accord.NET Framework")]
[assembly: AssemblyCopyright("Copyright © César Souza, 2009-2014")]
[assembly: AssemblyCompany("Accord.NET")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyVersion("2.12.0")]
[assembly: AssemblyInformationalVersion("2.12.0")]
[assembly: AssemblyFileVersion("2.12.0.4750")]
